### ISSUE TITLE
Rebase on FreeBSD 13.1

### ISSUE THREAD

**Issue by andreas-jonsson** [nomadbsd/NomadBSD#114]
Hi!

I have several laptops, most notably a [StarLab](https://starlabs.systems) coreboot laptop that won't boot with the default 13.0 image supplied on the website but when I rebuilt Nomad based on 13.1 they all run just fine. (Issues not specific to Nomad but FreeBSD as well.)

Updating Nomad on the USB stick directly can be tricky and it seems people have [varying success](https://forum.nomadbsd.org/t/freebsd-13-1/1023).

Perhaps providing an official 13.1 image on the website would be a good idea? (At least for people to test.)

Thanks

**Comment by grahamperrin** [comment]
> … won't boot with the default 13.0 image supplied on the website but when I rebuilt Nomad based on 13.1 they all run just fine. (Issues not specific to Nomad but FreeBSD as well.) …

https://forum.nomadbsd.org/t/nomadbsd-1-4-not-booting-on-some-hardware/689/13?u=grahamperrin includes a link to a relevant release note.

**Comment by grahamperrin** [comment]
Additional reasons to rebase on 13.1: 

* [UFS: soft update journaling, fsck_ffs (8) - NomadBSD Development - NomadBSD Forum](https://forum.nomadbsd.org/t/ufs-soft-update-journaling-fsck-ffs-8/872), in particular FreeBSD bug [256746 – fsck_ffs completely broken for background fsck 4](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256746)
* [259090 – UFS: bad file descriptor: soft update journaling can not be enabled on some FreeBSD-provided disk images – failed to write updated cg](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259090)

Context, my NomadBSD drive temporarily connected to a computer running FreeBSD 14.0-CURRENT: 

```text
root@mowa219-gjp4-8570p-freebsd:~ # lsblk da3
DEVICE         MAJ:MIN SIZE TYPE                                          LABEL MOUNT
da3              2:58   29G MBR                                               - -
  <FREE>         -:-   993K -                                                 - -
  da3s1          2:59   40M efi                                               - -
  da3s2          2:60  3.5G BSD                                               - -
    <FREE>       -:-   1.0M -                                                 - -
    da3s2a       2:62  3.5G freebsd-ufs                         label/nomadroot -
  da3s3          2:61   25G BSD                                               - -
    <FREE>       -:-   1.0M -                                                 - -
    da3s3a       2:63   25G freebsd-ufs                         label/nomaddata /tmp/nomaddata
  <FREE>         -:-   506K -                                                 - -
root@mowa219-gjp4-8570p-freebsd:~ # fstyp /dev/da3s2a
ufs
root@mowa219-gjp4-8570p-freebsd:~ # tunefs -j enable /dev/da3s2a
Using inode 14 in cg 0 for 29032448 byte journal
tunefs: Failed to write updated cg: Bad file descriptor
tunefs: soft updates journaling cannot be enabled
root@mowa219-gjp4-8570p-freebsd:~ # 
```

**Comment by andreas-jonsson** [comment]
Is there a need for help testing a new 13.1 image?
If so is there a specific area or feature to focus on?

**Comment by bsdlme** [comment]
We're almost ready for a RC1. Please be patient for another few days.

**Comment by mrclksr** [comment]
@andreas-jonsson, please see #128

**Comment by grahamperrin** [comment]
Time to close?
