### ISSUE TITLE
Change config/usr/bin/brightness_listener to use FreeBSD's backlight command

### ISSUE THREAD

**Issue by mrclksr** [nomadbsd/NomadBSD#122]
Instead of `intel-backlight`, use FreeBSD's `backlight` command (since 13.0), which allows setting brightness (backlight) even without X.

**Comment by bsdlme** [comment]
Good idea. I will need to test it on my notebooks.

**Comment by bsdlme** [comment]
`backlight` supports my T470s. I still need to upgdate `brightness_listener`

**Comment by bsdlme** [comment]
Implemented with https://github.com/nomadbsd/NomadBSD/commit/e53ca1dba27d97b332a7fd08354860828baa382f
