### ISSUE TITLE
(Question) NomadBSD uses ZFS?

### ISSUE THREAD

**Issue by hardBSDk** [nomadbsd/NomadBSD#124]
NomadBSD use ZFS as main filesystem? it doesn't reduce the USB drive life expectancy?

**Comment by mrclksr** [comment]
For the upcoming release we will provide an UFS and a ZFS image for amd64 and mac. ZFS is slower than UFS and will very likely wear out flash drives faster.

**Comment by Stratos-Crimson** [comment]
Do correct me If I am wrong but It won't do that by much tho, would It? Because It would be only writing checksums and reading data from flash memory doesn't wear It out.

**Comment by hardBSDk** [comment]
> Do correct me If I am wrong but It won't do that by much tho, would It? Because It would be only writing checksums and reading data from flash memory doesn't wear It out.

It depends, changes based on every USB hardware, there are better/worse hardwares out there with low write cycles limit.

Remember that ZFS fits well on SSDs because they have high write cycles limit, much more than USB devices.
