### ISSUE TITLE
I can't configure wifi , the version errata file can't be downloaded...

### ISSUE THREAD

**Issue by christhegreek** [nomadbsd/NomadBSD#14]
I can't configure wifi , the version errata file can't be downloaded...
also i tried to configure wifi networking i setup the rc.conf and loader.conf the wifi manager starts then but it doesn't show any networks !
Maybe i should try with another wifi adapter ? my adapter is fully compatible with freebsd without any configuration.

--Also because i'm greek and i can't even login if i select greek language please make the lighdm login so it uses only english/latin characters as input cause i can't login ! or setup the keyboard to change layout with alt+shift.

**Comment by mrclksr** [comment]
Hi @christhegreek,

> I can't configure wifi , the version errata file can't be downloaded...

Sorry for that. The mentioned link in the errata has just been corrected. If you still can't get your wifi to work, send us the output of
`pciconf -lv | grep -B3 -i network`

> --Also because i'm greek and i can't even login if i select greek language please make the lighdm login so it uses only english/latin characters as input cause i can't login ! or setup the keyboard to change layout with alt+shift.

Good point. Indeed, we were talking about the possibility to change the keyboard layout on the fly.

**Comment by christhegreek** [comment]
Also i have another question when i install nomadbsd on my disk the graphics card auto configuration will still popup every time i boot ?

**Comment by mrclksr** [comment]
> Also i have another question when i install nomadbsd on my disk the graphics card auto configuration will still popup every time i boot ?

From the [handbook](https://github.com/nomadbsd/handbook/blob/master/handbook.md#disablegfxmenu):
> If you want to disable the graphics driver menu, add
> 
> `initgfx_menu="NO"` to `/etc/rc.conf`.
>

**Comment by christhegreek** [comment]
Help guys ! how on earth i connect to wifi ?? the wifi manager does nothing
at all sees no networks if i create wpa supplicant it show up there but
does nothing how do i connect to internet ???????
Tried everything on freebsd guide but i can't see any wireless adapters
with ifconfig -a
Can you help cause i'm pretty stuck there !


Στις Τετ, 20 Νοε 2019 στις 2:13 μ.μ., ο/η mrclksr <notifications@github.com>
έγραψε:

**Comment by mrclksr** [comment]
Could you please post the output of the following commands?:
```
# grep -E 'wlan|ifconfig' /etc/rc.conf
# sysctl -n net.wlan.devices
# pciconf -lv | grep -B3 network
```
