### ISSUE TITLE
picom -b ?? Am I missing something here?

### ISSUE THREAD

**Issue by epsheldoni** [nomadbsd/NomadBSD#141]
I still have issues with multiple instances of picom after changing the dsbautostart-xF3CBL.desktop file.  
The man page for picom -b states   

     -b, --daemon
           Daemonize process. Fork to background after initialization. This
           option can only be set from the command line, setting this in the
           configuration file will have no effect.

Am I missing something here?

After logging in, the  dunes graphic stays and I have to ctrl-alt-F2 to get to a terminal and log in.  
The desktop comes up after logging in, but the autostart for conky is not done.

**Comment by mrclksr** [comment]
Hi @epsheldoni,

delete `dsbautostart-xF3CBL.desktop`. The problem is that the `picom` port started to provide its own autostart file.
