### ISSUE TITLE
Small Bug in Contact page

### ISSUE THREAD

**Issue by Sumitwarrior7** [nomadbsd/NomadBSD#143]
There is a small bug i found in the contact page where there are errors :
[at] , [dot]  are used , but it should be replaced by @ .

**Comment by Sumitwarrior7** [comment]
![Screenshot from 2023-10-22 18-44-24](https://github.com/nomadbsd/NomadBSD/assets/108853577/febeb0be-5985-4652-9997-ca5486fab950)

**Comment by bsdlme** [comment]
This is done intentionally to mitigate automated spam bots.
