### ISSUE TITLE
freebsd-update WorkDir default

### ISSUE THREAD

**Issue by robb-randall** [nomadbsd/NomadBSD#19]
After installing from a live usb to a hard drive, I ran `# freebsd-update fetch` on the newly installed system and received:
> freebsd-update: Directory does not exist or is not writable: /home/freebsd-update

I found that the default WorkDir after the installation set to _/home/freebsd-update/_ in freebsd-update.conf.  Changing this value to _/var/db/freebsd-update/_ enables freebsd-update to run without errors.

**Comment by mrclksr** [comment]
Thank you, Robb.
