### ISSUE TITLE
Boot to cli prompt, compilation errors line 89 - MacBook Pro

### ISSUE THREAD

**Issue by wrightmac** [nomadbsd/NomadBSD#22]
I have a MacBook Pro, 16GB, running 10.12 on the Mac side. I was trying to get nomadbsd on a VM and it came up with the following error. 

String found where operator expected at /usr/libexec/nomadbsd-set
line 89, near "'midori  Lighweight web browser using WebKit
browser engine'"
(Missing semicolon on previous line?)
syntax error at /usr/libexec/nomandbsd-setup line 89, near
"'midori  Lighweight web browser using WebKit
browser engine'"
Execution of /usr/libexec/nomadbsd-set aborted due to compliation errors.

I also tried booting the Mac from the USB drive with the same error.

**Comment by mrclksr** [comment]
Thank you for reporting, @wrightmac
