### ISSUE TITLE
Latest live halts during boot...

### ISSUE THREAD

**Issue by yochanon** [nomadbsd/NomadBSD#26]
I earlier this morning put 1.3-RC1 on a good Samsung 124GB flashdrive using dd.

After booting to that drive via the bios of my system (information of it attached), it boots fine all the way to the point of the choices, eg multiuser, single user, etc.

By choosing 'multiuser' then trying with 'single user' and then trying again by letting the timer run out and letting it boot itself, it *always* stopped at a point with this:

`/dev/label/nomadroot: cannot read blk 7516136
/dev/label/nomadroot: unexpected soft update inconsistancy; run fsck manually
automatic file system check failed! Help!`

This happened consistently, even when I created the geli /home. It *always stopped at that point and with that same blk number. And when it left me with a 'do you want to continue: y/n' type of question, the yes just keeps asking you to run an fsck manually, while answering no takes you a a blank prompt, where I simply 'rebooted' and went back into my normal system/OS.

The flashdrive is good because I used it for a liveslak (Slackware 14.2 live, persistant *and* a Slackware current, which is back on the drive at this moment).

My system information is attached.
[computer info.txt](https://github.com/nomadbsd/NomadBSD/files/3869252/computer.info.txt)

**Comment by mrclksr** [comment]
Is the image's sha256 checksum correct?
Did this happen at the very first boot, before running the setup?

**Comment by yochanon** [comment]
On Wed, 20 Nov 2019 05:10:30 -0800
mrclksr <notifications@github.com> wrote:

> Is the image's sha256 checksum correct?
> Did this happen at the very first boot, before running the setup?
> 
> 

  Yessir, the checksum is correct.

  Ah, sorry, I forgot to add that...it does it *after* one has done one's setup
  and is asked to 'reboot', when everything looks okay. It's after the reboot
  that it halts with the problem I wrote about. I believe the *only* thing I
  changed during the setup, was the language to 'English' (USA, or whatever it
  was). Everything else during setup I was able to leave alone and just click
  'next', if i remember right.

  Again, my apologies for completely missing that step.

  If the above is still not enough to go on, I could probably take a picture of
  each step with my phone and put them all in a tarball (I can use what I need
  to to make them a nice small file size but remain large enough to view easily)
  so that I can then send it as another attachment. Just let me know and I'll do
  whatever is needed.

  I'd really like to get my hands on a BSD that has a DE already installed so I
  don't have to futz around afterward trying to figure out how to do it, heh heh.

	Yochanon

**Comment by mrclksr** [comment]
There are usually two reasons for an error like this:
1. The filesystem was not properly unmounted due to
a. a crash
b. power failure/switching the system off (or resetting) without proper shutdown
c. the device was detached before unmounted
2. Disk error

You can try the following:
1. Boot the system into single-user mode by choosing '2' in the boot menu.
2. When asked for the shell's pathname press ENTER.
3. Run ````fsck -y````. Rerun that command if needed.
4. Reboot

If that didn't help, ````dd```` the image to your flash drive again, and start anew (if you haven't already). If this error still persists, try another flash drive.

**Comment by yochanon** [comment]
Okay, I tried those things and it always was the same error.

Then, for the heck of it I tried it on another flashdrive of 64GB and all was well. I don't understand why the liveslak (Slackware current, persistent) works on the the problem-giving flashdrive, but it does. Oh well, at least we got it figured out.

Thank you for your patience and time.
