### ISSUE TITLE
Any plans for supporting more desktop environments?

### ISSUE THREAD

**Issue by time-killer-games** [nomadbsd/NomadBSD#30]
KDE specifically would be especially cool IMO. But I do feel it's a bit over-complicated to install the original FreeBSD. That's something I really appreciate about NomadBSD; it's installation is much simpler and comprehensive, much like how most Linux distro's are installed these days. :)

I feel if more people knew about Nomad, and if it had a wider selection of DE's, more people from the Linux world would consider switching to BSD. To be honest, I tried installing FreeBSD several times now and was very unsuccessful and had no idea what i was doing. Nomad is much better.

**Comment by mrclksr** [comment]
Thank you for the feedback. You can install other DEs by yourself, but we won't support them. Here is what I did to install KDE on NomadBSD:
```
# pkg install kde5 sddm
# sysrc sddm_enable=YES
# sysrc slim_enable=NO
# sysrc hald_enable=YES
# echo "proc                     /proc procfs rw           0 0" >> /etc/fstab
# reboot
```
Installing 427 packages took a while. It runs OK, and everything was working as far as I tested it, but it's way too heavy for me.

**Comment by time-killer-games** [comment]
This is great! Yeah, i figured just like Linux it would be as simple as a terminal command. This is simple enough once you know the right steps it it's much different from having KDE out of the box, since all the packages need to be downloaded and installed either way.

Thank you!
