### ISSUE TITLE
Boot loop after configuration

### ISSUE THREAD

**Issue by IamPhotor** [nomadbsd/NomadBSD#48]
I have downloaded NomadBSD 1.3 and dd'ed the img to a Verbatim 16 Gb USB-stick. The stick booted my ThinkPad T440s and I did the configuration (Germany, German keyboard (no dead), fish, vim, gvim, Thunar). The configuration started but after "Creating filesystem on /dev/label/nomadhome" I get an error: " "newfs -t -E -U -O 1 -o time -b 32768 -f 4096 -m 8 /dev/label/nomadhome" failed"
and I end up in a boot loop. I can start the stick in single user mode, though. This is true for encrypted /home as well as for unencrypted)

Attached pictures show the output of "gpart list" and "geom -t" (unfortunately, only as photo taken from screen).
PS: installation on other sticks (8 GB, Sandisk 64 Gb seem to work) 

![20-01-01 18-58-34 0939](https://user-images.githubusercontent.com/59445534/71673877-2cda8580-2d7a-11ea-948f-61a9214ae011.jpg)
![20-01-01 18-58-57 2C71](https://user-images.githubusercontent.com/59445534/71673882-2fd57600-2d7a-11ea-907e-53ca4809bec5.jpg)

**Comment by mrclksr** [comment]
This is most likely caused by a hardware error. You could test your USB stick with `badblocks` from a FreeBSD or Linux system.

**Comment by bsdlme** [comment]
Closed because feedback timeout.
