### ISSUE TITLE
Disk install sudoers

### ISSUE THREAD

**Issue by robb-randall** [nomadbsd/NomadBSD#50]
When installing to disk the sudoers file is not updated with the specified username when changing  from the default nomad username.  I was able to:
```
NomadBSD:/home/robb% su                       
Password:
root@NomadBSD:/home/robb # visudo
```
Then replaced `nomad ALL=(ALL) ALL` with `robb ALL=(ALL) ALL`

**Comment by mrclksr** [comment]
Thank you, Robb. We will fix that.

**Comment by mrclksr** [comment]
[Fixed](https://github.com/nomadbsd/NomadBSD/commit/9120838c39da3a6dc793ed86df61264c72895284)
