### ISSUE TITLE
Trackpad doesn't work on surface go's type cover

### ISSUE THREAD

**Issue by aspyct** [nomadbsd/NomadBSD#54]
Hi there,

I'm playing with my new surface go, and nomadbsd starts just fine on it.
It's the 4GB RAM model, as depicted here: https://www.microsoft.com/en-us/p/surface-go/8V9DP4LNKNSZ/L8M8?activetab=pivot%3aoverviewtab

The keyboard on the type cover works just fine, but the trackpad doesn't do anything, neither click the mouse not move it.

How can I go about debugging this? I would really love to use nomadbsd on this machine!

**Comment by mrclksr** [comment]
Hi @aspyct,

it seems that the trackpad/touchpad is connected via USB. If the `ums` driver is not loaded (`kldstat | grep ums`), add the line `ums_load="YES"` to `/boot/loader.conf`, and reboot.

**Comment by aspyct** [comment]
Ha, it works! Brilliant :+1: Thanks

Note that the type cover occasionally disconnects, and it makes typing a bit of a pain. All is good with a traditional keyboard attached to USB though.
