### ISSUE TITLE
dsb* won't run after pkg upgrade (Qt library problem)

### ISSUE THREAD

**Issue by nicolashainaux** [nomadbsd/NomadBSD#63]
Hello,

After having performed `pkg update` and `pkg upgrade`, I noticed I couldn't change the wallpaper anymore. Actually, `dsbbg` does not start (I could set it via `feh`).

Then after next reboot, no mixer, removable device manager nor anything but the date and time did show up in the notifications tray up right. And indeed, I get:

    nomad@NomadBSD ~> dsbbg
    Cannot mix incompatible Qt library (version 0x50d02) with this library (version 0x50e02)
    fish : Tâche , 'dsbbg' terminée par le signal SIGABRT (Abandon)
    nomad@NomadBSD ~ [SIGABRT]> dsbmc
    Cannot mix incompatible Qt library (version 0x50d02) with this library (version 0x50e02)
    fish : Tâche , 'dsbmc' terminée par le signal SIGABRT (Abandon)
    nomad@NomadBSD ~ [SIGABRT]> dsbmixer
    Cannot mix incompatible Qt library (version 0x50d02) with this library (version 0x50e02)
    fish : Tâche , 'dsbmixer' terminée par le signal SIGABRT (Abandon)
    nomad@NomadBSD ~ [SIGABRT]>

Maybe it is worth to add that I changed the `pkg` configuration to follow `latest` instead of `quarterly`. I don't know if this is relevant.

**Comment by mrclksr** [comment]
Hi @nicolashainaux,

[this problem is caused by qt5-style-plugins](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246502). Try
````
# pkg update -f
# pkg upgrade
````
If that doesn't help, you can build qt5-style-plugin from ports:
````
# mkdir /home/ports
# ln -s /home/ports /usr
# svnlite co https://svn.freebsd.org/ports/head/Mk /usr/ports/Mk
# svnlite co https://svn.freebsd.org/ports/head/Templates /usr/ports/Templates
# svnlite co https://svn.freebsd.org/ports/head/x1-themes/qt5-style-plugins /tmp/qt5-style-plugins
# cd /tmp/qt5-style-plugins
# make DISTDIR=/tmp deinstall install
````

**Comment by nicolashainaux** [comment]
Thank you very much!
Using `pkg` was not enough, I had to build qt5-style-plugin. But then everything was back there at reboot.

Thanks a lot for this stunning project, by the way!

**Comment by mrclksr** [comment]
> Thanks a lot for this stunning project, by the way!

Thank you :)
