### ISSUE TITLE
Correct way to upgrade base system?

### ISSUE THREAD

**Issue by nicolashainaux** [nomadbsd/NomadBSD#64]
Hello!

Sorry to come back for another question, but reading [this thread](https://forum.nomadbsd.org/t/how-to-update-an-existing-usb-image/80) from the forum, I feel quite unsure as to the correct way to upgrade the base system.

Is it reliable to use, as in FreeBSD, `freebsd-update fetch` and `freebsd-update install`? If not, what is the way to do this?

**Comment by mrclksr** [comment]
You can run `freebsd-update fetch install` as in a regular FreeBSD installation.

**Comment by nicolashainaux** [comment]
Thank you very much!!
