### ISSUE TITLE
How to properly configure a Xfce or Lumina session?

### ISSUE THREAD

**Issue by probonopd** [nomadbsd/NomadBSD#71]
How would one go about properly installing and configuring a Xfce or Lumina session including a session manager and autologin? One should be able to select, from the login screen (if autologin is disabled or the user manually logged out of the session) to choose another desktop environment.

The current way in which NomadBSD hardcodes things like `openbox-session` in `~/.xinitrc` seems a bit hackish to me. Isn't one supposed to use `/etc/...` and a login manager for system-wide configuration like that?

**Comment by probonopd** [comment]
One reason I am asking is that I _totally_ need icons on the desktop:

![image](https://user-images.githubusercontent.com/2480569/91617388-3c9d7e80-e988-11ea-8ce3-5ad62e421cdb.png)

**Comment by a-bateman** [comment]
After installing xfce comment out line 55 of ~/.xinit.rc to start xfce.  Also make sure you comment out line 68 to prevent openbox from running.

**Comment by probonopd** [comment]
Thank you. I have since been working on helloSystem (including a desktop that shows icons on the desktop), so I am closing this ticket.
