### ISSUE TITLE
Running applications not shown in the "Dock" 

### ISSUE THREAD

**Issue by probonopd** [nomadbsd/NomadBSD#73]
Running applications are not shown in the Plank "Dock". For example, here I am running Inkscape yet its icon is absent from the "Dock":

![none](https://user-images.githubusercontent.com/2480569/91618168-f5b08880-e989-11ea-95ba-05a6fb79f100.png)

**Comment by mrclksr** [comment]
If you want that behaviour, open the *plank preferences* (hold \<CTRL\> and right-click on an icon). Enable *Show Unpinned* under *Behaviour*.

**Comment by probonopd** [comment]
Thanks for the hint @mrclksr. Could this be made the default? I think it is what most users would expect, coming from other systems such Windows, Mac, Xfce and so on.

By the way, the German translation for this configuration item is completely incomprehensible, but I guess I will report this upstream.

![plank](https://user-images.githubusercontent.com/2480569/91632009-25897b80-e9de-11ea-9a77-8859ab37d2e9.png)

**Comment by bsdlme** [comment]
I agree with @probonopd. This should be the default setting.

**Comment by probonopd** [comment]
Thank you very much @mrclksr :+1: These small touches are really important for newcomers.
