### ISSUE TITLE
Enable a "real desktop" by default

### ISSUE THREAD

**Issue by probonopd** [nomadbsd/NomadBSD#74]
Most desktop environments allow users to have icons on the desktop. Like this:

![image](https://user-images.githubusercontent.com/2480569/91619490-745af500-e98d-11ea-9af0-b55cb6d480ff.png)

As per https://twitter.com/NomadBSD/status/1299469685562499075 the solution is to run `pcmanfm --desktop` (which happens to be already installed).

I'd ask to make launching this the default, so that the desktop gets the functionality known to users from most desktop environment like Windows, the Mac, Xfce, etc.

Reference:
https://forum.nomadbsd.org/t/shortcut-icons-on-the-desktop/274

**Comment by bsdlme** [comment]
I think it's a good idea to enable the desktop. Maybe without any pre-set icons, though.

**Comment by probonopd** [comment]
I've since implemented this over at https://github.com/helloSystem/. This is my current desktop I am typing this on:

![image](https://user-images.githubusercontent.com/2480569/99914605-ca2a0980-2cfe-11eb-9e7e-739691f16ad7.png)

Hence closing here.
