### ISSUE TITLE
Consider using TearFree for Intel?

### ISSUE THREAD

**Issue by probonopd** [nomadbsd/NomadBSD#81]
Should we consider using TearFree for Intel?

Please see https://forums.freebsd.org/threads/intel-video-and-screentearing.72085/#post-438483 for more information, including some `/boot/loader.conf` options to make it (as the poster writes) "fast and buttersmooth. NO screen tearing".

**Comment by wesbluemarine** [comment]
Remember that TearFree is available only for the old intel driver, not for "modesetting".
https://bugs.freedesktop.org/show_bug.cgi?id=98876

**Comment by probonopd** [comment]
Thanks @wesbluemarine, I wasn't aware. In case this makes TearFree worthless for NomadBSD feel free to close this issue.
