### ISSUE TITLE
Disable initgfx from the bootloader?

### ISSUE THREAD

**Issue by probonopd** [nomadbsd/NomadBSD#83]
Is there a way to disable initgfx from the bootloader, e.g., by setting or unsetting a variable in the bootloader?

I know that one can disable initgfx by adding `initgfx_enable="NO"` to `/etc/rc.conf` but this is not possible on purely read-only systems such as helloSystem.

**Comment by mrclksr** [comment]
There is a `initgfx.detect.disable` loader variable which prevents `initgfx` from autodetecting graphics cards if set to `1`. It just writes a Xorg config file for a non-accelerated driver (VESA or SCFB). If the filesystem is completely r/o, `initgfx` can't even do that, and is therefore disabled.

**Comment by probonopd** [comment]
Thanks, `set initgfx.detect.disable=1` is exactly what I was looking for. (There being `kenv` and `sysctl` parallel universes in FreeBSD still confuses me to this day.)
