### ISSUE TITLE
Build Fails 

### ISSUE THREAD

**Issue by danielmalencar** [nomadbsd/NomadBSD#88]
My FreeBSD installed is 13.0 releng/13.0-n244733-ea31abc261
![image](https://user-images.githubusercontent.com/25048796/119613873-fcaedf00-bdd3-11eb-99b8-187844f0325a.png)

**Comment by danielmalencar** [comment]
Can you help me?

**Comment by danielmalencar** [comment]
@mrclksr

**Comment by mrclksr** [comment]
Hi @danielmalencar,

there is a problem with fetching the distfile for the drm-kmod port for some reason. There is nothing I could do about it. The problem might be temporarily. Try to resume the build later with `./build resume`. Maybe updating the ports tree helps.

**Comment by danielmalencar** [comment]
Thanks for answering. But when I give the command manually pkg install drm-kmod it works. It is already installed. I no longer know what to do to resolve it.
![image](https://user-images.githubusercontent.com/25048796/119741882-fdd81e80-be5c-11eb-80ad-81622bd096f8.png)

**Comment by danielmalencar** [comment]
I solved with 
# portsnap fetch
# portsnap extract
