### ISSUE TITLE
change uname output from FreeBSD to NomadBSD

### ISSUE THREAD

**Issue by danielmalencar** [nomadbsd/NomadBSD#89]
I would like to change uname output from FreeBSD to NomadBSD.
I changed the /work/src/sys/conf/newvers.sh file before buildkernel, but it had no effect.
How to proceed?

**Comment by mrclksr** [comment]
`uname` retrieves its information about the OS type, version, etc. from the environment and the `sysctl` variables. If you want to
change the OS type, you can either set it via the `UNAME_s` environment variable (`UNAME_s=NomadBSD uname -s), or you
can set `kern.ostype=NomadBSD` in `/etc/loader.conf`. After a reboot, `uname -s` should show `NomadBSD`

**Comment by danielmalencar** [comment]
UNAME_s=NomadBSD give me command not found.
And add kern.ostype=NomadBSD give me this
![image](https://user-images.githubusercontent.com/25048796/120370189-a4ec0880-c2ea-11eb-8095-358c566eaac3.png)

**Comment by danielmalencar** [comment]
And...
![image](https://user-images.githubusercontent.com/25048796/120370511-0b712680-c2eb-11eb-9760-e08f6fad5c45.png)

**Comment by mrclksr** [comment]
> UNAME_s=NomadBSD give me command not found.

This works with Bourne shell compatible shells. In (t)csh it is `setenv UNAME_s NomadBSD; uname -s`.

> And add kern.ostype=NomadBSD give me this

Ok, this is ... interesting.

> And...

`kern.ostype` can only be set via `/boot/loader.conf`, or from the loader prompt.

**Comment by danielmalencar** [comment]
> setenv UNAME_s NomadBSD; uname -s

Sorry! This is works perfectly setenv UNAME_s NomadBSD; uname -s thank you very much!

**Comment by danielmalencar** [comment]
But how to make this change permanent in nomadbsd build file?

**Comment by danielmalencar** [comment]
Every time I restart, the original information is restored

**Comment by mrclksr** [comment]
> Every time I restart, the original information is restored

It's just an environment variable which is, in this case, only visible to the current shell and all processes started from it. See `man environ` for more information.

**Comment by danielmalencar** [comment]
> > Every time I restart, the original information is restored
> 
> It's just an environment variable which is, in this case, only visible to the current shell and all processes started from it. See `man environ` for more information.

I believe that modifying the work/sys/usr/sys/conf/newvers.sh file right after the nomadbsd updatebase is the best option

**Comment by danielmalencar** [comment]
after updatebase and before buildkernel
