### ISSUE TITLE
Package deletion/removal/uninstallation is screwed, system bricked

### ISSUE THREAD

**Issue by a-p-jo** [nomadbsd/NomadBSD#92]
Maybe this isn't NomadBSD side issue , but :

Using `pkg delete <package_name>...` or `pkg remove ...` or remove option in `octopkg` results in the deletion of given package and **ALL** packages that depend on it, by default (clean install).

What sort of package management is this  🤣  😭  , ruined my install by removing everything (even `X`) except FreeBSD base. You want to replicate the bug, dev ? Try `sudo pkg delete perl5 -y` and find almost everything (because everything depends on perl) removed. 

Please fix this or if this a noob mistake tell me what I ought to do - I expected package management to work like it does everywhere else : You tell the package manager to remove a bunch of packages and unless forced it throws an error and fails if those packages are being depended on. Not simply delete everything depending on it 😱 .

**Comment by clausecker** [comment]
Works as designed.  From **pkg-delete**(8)

     If the set of packages to be deleted would leave installed packages with
     unfulfilled dependencies, pkg delete will add the packages with
     unfulfilled dependencies to the list of packages to be deleted, unless
     forced to proceed without deleting any other packages by the -f option.

I really don't understand why anybody would pass `-y` to `pkg-delete` to suppress the `y/n` prompt.  The whole point of this prompt is to avoid unintentional deletion of reverse dependencies.

**Comment by a-p-jo** [comment]
It was my bad for getting the wrong (old) manual.
